services:
  api:
    container-name: kd-api
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - KEY=MangoMango123MangoMango321
    ports: 
      - "5000:80"
    depends_on:
      - migrations

  migrations:
    container_name: service-migrations
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    depends_on: 
        - db

  db:
    container_name: kd-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
       - MSSQL_PID=Express
       - MSSQL_SA_PASSWORD=Roastcinnamon123
       - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

    #command: docker run --name db -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=yourStrongPassword(!)123' -p 1433:1433 mcr.microsoft.com/mssql/server:2022-latest