services:
  dotnet-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
    - KEY=roastedcinnamon
    ports: 
      - "5000:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Roastcinnamon@123."
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"