services:
  kindle-decision:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
       KEY: "ThisApiWasCreatedByChristopherWamae"
    ports: 
      - "5000:80"
    depends_on:
      - migrations

  migrations:
   container_name: service-migrations
   image: service-migrations
   build:
     context: .
     dockerfile: Dockerfile
     target: migrations
   depends_on: 
       - db

   

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        MSSQL_SA_PASSWORD: i34i.ad.AC
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"