services:
  kindle-decision:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
       KEY: MangoMango123MangoMango321
    ports: 
      - "5000:80"
    depends_on:
      - migrations

  migrations:
    container_name: service-migrations
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    depends_on: 
        - db 

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
        MSSQL_SA_PASSWORD: yourStrong(!)Password123
        ACCEPT_EULA: Y
    ports:
      - "1433:1433"