services:
  kindle-decision:
    build:
      context: .
      args:
        - KEY=${KEY}
      dockerfile: Dockerfile
    environment: 
       - KEY
    ports: 
      - "5000:80"
    depends_on:
      - migrations

  migrations:
   container_name: service-migrations
   image: service-migrations
   build:
     context: .
     dockerfile: Dockerfile
     target: migrations
   depends_on: 
       - db

   

  db:
    image: "mcr.microsoft.com/mssql/server"
    build:
        args:
        - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
        - ACCEPT_EULA=${ACCEPT_EULA}
    environment:
        - MSSQL_SA_PASSWORD
        - ACCEPT_EULA
    ports:
      - "1433:1433"