services:
  kindle-decision:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
       KEY: ${KEY}
    ports: 
      - "5000:80"
    depends_on:
      - migrations

  migrations:
    container_name: service-migrations
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    depends_on: 
        - db 

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        MSSQL_SA_PASSWORD: "Roastcinnamon123"
        ACCEPT_EULA: ${ACCEPT_EULA}
    ports:
      - "1433:1433"